development:
   adapter: mysql
   database: tezbazaari_dev
   username: root
   password: tezbazaari
   host: localhost

test:
   adapter: mysql
   database: tezbazaari_test
   username: root
   password: tezbazaari
   host: localhost

production:
   adapter: mysql
   database: tezbazaari_prod
   username: root
   password: tezbazaari
   host: localhost
